### ISSUE TITLE
Quest page frontend updates

### ISSUE THREAD

**Issue by RiverRuby** [nfc-denver/nfc-denver#103]
- [x] Implemented pinning button + display, store pinning status in localStorage
- [x] Make sure the progress bars re-animate every time you return to page, right now they only animate/display on the first visit
- [x] Implement location requirement screen with multiple locations, where you can click on a location to see its details (Screen 47)

**Comment by kalidiagne** [comment]
>  Make sure the progress bars re-animate every time you return to page, right now they only animate/display on the first visit 

 fixed here https://github.com/nfc-denver/nfc-denver/pull/108

**Comment by AndrewCLu** [comment]
Closed by #121
